---
# vars file for win-patches-installed

win_patch_report: C:\ansible_Installed_patch_report.csv
win_patch_report_file: C:\ansible_Installed_patch_report.csv
playbook_role_dir: "~/win-patch-update/roles/win-patches-installed/files"
