---
- name: Copy Script to Reset Windows Update Components
  win_copy:
     src: files/ResetWUEng
     dest: C:\Temp\
     #remote_src: yes   

- name: Execute windows script
  win_shell: C:\Temp\ResetWUEng


# Search and return list of patch updates
- name: Search and return list of patch updates found in {{ win_patch_report }}
  win_updates:
    category_names:
     - SecurityUpdates
     - CriticalUpdates
     - UpdateRollups
    state: searched
    log_path: '{{ win_patch_report }}'
  register: patch_report

- debug:
    var: patch_report

- name: Remove Windows Script
  win_file:
    path: C:\Temp\ResetWUEng
    state: absent

- name: Fetch Windows Patch Report to Ansible Controller
  win_copy:
     src: /tmp
     dest: "{{ win_patch_report_file }}"
     remote_src: yes

- name: Read users from CSV file and return a list
  read_csv:
    path: '{{ win_patch_report }}'
    fieldnames: Date,Clasification,Title
    delimiter: '  '
  register: report
  delegate_to: localhost
